//
//  Card.m
//  CardGame
//
//  Created by Adriana Pineda on 10/8/21.
//

#import "Card.h"

@implementation Card

// Autogenerated by the use of @property
//@synthesize contents = _contents; // @synthesize is used to specify the name of the instance variable
//
//- (NSString *)contents {
//    return _contents;
//}
//
//- (void)setContents:(NSString *)contents {
//    _contents = contents;
//}


// we can use [] notation for getter and setter methods => i.e [card contents]
// dot notation is clearer and widely used, but [] is not wrong.
// As long as we are consistent we could use either

// we *could* use dot notation for a method that doesn't take any arguments, the compiler
// will show a warning, but we should never use it. Only use dot notation for setters and getters

- (int)match:(NSArray *)cards {
    int score = 0;

    for (Card *card in cards) {
        if ([card.contents isEqualToString:self.contents]) { // == compares pointers, not the contents of the pointers
            score = 1;
        }
    }

    return score;
}

@end
